/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Authentification;
  GtkWidget *Espace_Admin;
  GtkWidget *Gestion_utilisateur;
  GtkWidget *Gestion_des___lections;
  GtkWidget *Gestion_du_bureau_de_vote;
  GtkWidget *Gestion_Observateur;
  GtkWidget *vote;
  GtkWidget *window2_afficher;
  GtkWidget *window_ajouteravec_succes;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  Authentification = create_Authentification ();
  gtk_widget_show (Authentification);
  Espace_Admin = create_Espace_Admin ();
  gtk_widget_show (Espace_Admin);
  Gestion_utilisateur = create_Gestion_utilisateur ();
  gtk_widget_show (Gestion_utilisateur);
  Gestion_des___lections = create_Gestion_des___lections ();
  gtk_widget_show (Gestion_des___lections);
  Gestion_du_bureau_de_vote = create_Gestion_du_bureau_de_vote ();
  gtk_widget_show (Gestion_du_bureau_de_vote);
  Gestion_Observateur = create_Gestion_Observateur ();
  gtk_widget_show (Gestion_Observateur);
  vote = create_vote ();
  gtk_widget_show (vote);
  window2_afficher = create_window2_afficher ();
  gtk_widget_show (window2_afficher);
  window_ajouteravec_succes = create_window_ajouteravec_succes ();
  gtk_widget_show (window_ajouteravec_succes);

  gtk_main ();
  return 0;
}

